CREATE TABLE directors (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  director_name VARCHAR(250) UNIQUE NOT NULL,
  deleted_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);